baseurl: ""
url: http://technicalrex.com
#baseurl: /technicalrex.com
#url: http://technical-rex.github.io

title: Technical Rex
description: A site about programming, business, and dinosaurs. ROAR!

google_analytics: UA-62666024-3

tag_permalink_style: pretty
tag_page_layout: tag
tag_page_dir: tag

tag_descriptions:
    pegger: >
        Pegger is a turn-based peg jumping game. The following posts form a tutorial
        series covering data modeling, API design, and server- and client-side implementation
        using Java, Google App Engine, Bootstrap, and AngularJS.

authors:
    erik:
        name: Erik Gillespie
        signature: Erik
        # Icons
        email_address: erik.gillespie@gmail.com
        bitbucket:
        dribbble:
        facebook:
        flickr:
        github: egillespie
        google_plus: +ErikGillespie
        gravatar_hash: 77e0d1571ed8fd1f9249a01e7569db05
        instagram:
        linkedin: https://www.linkedin.com/in/eriklgillespie
        pinterest: erikgillespie
        reddit: elgillespie
        stack_exchange: http://stackoverflow.com/users/1696044/erik-gillespie
        steam: 76561198029980002
        tumblr: elgillespie
        twitter: eriklgillespie
        wordpress:
        youtube: ErikGillespie

paginate: 5
paginate_path: "blog/page:num"

kramdown:
    input: GFM

sass:
    sass_dir: _sass
    style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
